### PyCaret documentation to be found at https://pycaret.readthedocs.io/en/latest/api/classification.html

# Setting up environment

In [1]:
import pandas as pd, numpy as np
%matplotlib inline

#setting to displaying all columns in pandas df
pd.set_option("display.max_columns", None)

## Load data

In [2]:
# Data generated in '2.0-random_forest'
dataset = pd.read_csv('../results/2.0-random_forest_train_test.csv', index_col=0)

In [3]:
dataset.head()

,AGE,RAVLT_immediate,AVDEL30MIN_neuro,AVDELTOT_neuro,TRAASCOR_neuro,TRABSCOR_neuro,CATANIMSC_neuro,GDTOTAL_gds,ANARTERR_neuro,LRHHC_n_long,Apoe4_,Subgroup_,Subgroup_num_,Usage_,PTGENDER,Gender_num_
13,80.0,36.0,1.0,8.0,47.0,139.0,16.0,1.0,4.0,0.003458,0.0,cAD,1,train,Female,1
26,76.8,27.0,5.0,10.0,61.0,300.0,19.0,4.0,23.0,0.005251,0.0,sMCI,0,train,Male,0
29,70.9,22.0,0.0,0.0,18.0,145.0,18.0,2.0,12.0,0.003026,1.0,cAD,1,train,Female,1
37,72.8,29.0,1.0,8.0,40.0,101.0,17.0,1.0,6.0,0.002767,0.0,cAD,1,train,Male,0
55,77.6,30.0,2.0,14.0,150.0,300.0,12.0,0.0,9.0,0.002814,0.0,cAD,1,train,Male,0

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 678 entries, 13 to 6309
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AGE               678 non-null    float64
 1   RAVLT_immediate   678 non-null    float64
 2   AVDEL30MIN_neuro  678 non-null    float64
 3   AVDELTOT_neuro    678 non-null    float64
 4   TRAASCOR_neuro    678 non-null    float64
 5   TRABSCOR_neuro    678 non-null    float64
 6   CATANIMSC_neuro   678 non-null    float64
 7   GDTOTAL_gds       678 non-null    float64
 8   ANARTERR_neuro    678 non-null    float64
 9   LRHHC_n_long      678 non-null    float64
 10  Apoe4_            678 non-null    float64
 11  Subgroup_         678 non-null    object
 12  Subgroup_num_     678 non-null    int64
 13  Usage_            678 non-null    object
 14  PTGENDER          678 non-null    object
 15  Gender_num_       678 non-null    int64
dtypes: float64(11), int64(2), object(3)
memory usage: 90.0+ KB

> 678 instanser, ingen missing vales

In [5]:
dataset.Usage_.value_counts()

train    539
test     139
Name: Usage_, dtype: int64

539 for trening, 139 for test

In [6]:
dataset['Subgroup_'].value_counts()

sMCI    357
cAD     321
Name: Subgroup_, dtype: int64

# Prepare data

**ToDo's:**
1. Make sure the cross-validation on train set is exactly the same as used in RandomForest 
2. Run `setup` with the the correct vaildation folds and the spesified test data (defined in script X and selected by `Usage_`)

## Split trening og test

Specified in `Usage_`-column

In [7]:
data = dataset.loc[dataset.Usage_=='train']
data_unseen = dataset.loc[dataset.Usage_=='test']

In [8]:
data_unseen.head()

,AGE,RAVLT_immediate,AVDEL30MIN_neuro,AVDELTOT_neuro,TRAASCOR_neuro,TRABSCOR_neuro,CATANIMSC_neuro,GDTOTAL_gds,ANARTERR_neuro,LRHHC_n_long,Apoe4_,Subgroup_,Subgroup_num_,Usage_,PTGENDER,Gender_num_
6,80.4,30.0,1.0,7.0,49.0,168.0,13.0,0.0,17.0,0.003638,0.0,sMCI,0,test,Female,1
82,77.3,29.0,0.0,11.0,122.0,151.0,17.0,2.0,3.0,0.003343,1.0,cAD,1,test,Male,0
184,77.5,35.0,1.0,10.0,27.0,69.0,24.0,2.0,22.0,0.003149,1.0,cAD,1,test,Female,1
359,71.1,24.0,0.0,2.0,50.0,85.0,13.0,2.0,7.0,0.003729,0.0,cAD,1,test,Female,1
384,83.6,30.0,2.0,9.0,22.0,76.0,18.0,0.0,9.0,0.003700,0.0,cAD,1,test,Female,1

In [9]:
print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

Data for Modeling: (539, 16)
Unseen Data For Predictions: (139, 16)

## Seting up crossvalidation specified in `2.0-random_forest` notebook

> NB! Using the exact same cross validation folds as specicified in the previous script.

***Load cross validation folds specified in notebook `2.0-random_forest.ipynb`***

In [10]:
cv_folds = pd.read_csv('../results/2.0-random_forest_kfolds.csv', index_col=0)

In [11]:
cv_folds.head()

,SKF_CV10_F00_,SKF_CV10_F01_,SKF_CV10_F02_,SKF_CV10_F03_,SKF_CV10_F04_,SKF_CV10_F05_,SKF_CV10_F06_,SKF_CV10_F07_,SKF_CV10_F08_,SKF_CV10_F09_,SKF_CV20_F00_,SKF_CV20_F01_,SKF_CV20_F02_,SKF_CV20_F03_,SKF_CV20_F04_,SKF_CV20_F05_,SKF_CV20_F06_,SKF_CV20_F07_,SKF_CV20_F08_,SKF_CV20_F09_,SKF_CV20_F10_,SKF_CV20_F11_,SKF_CV20_F12_,SKF_CV20_F13_,SKF_CV20_F14_,SKF_CV20_F15_,SKF_CV20_F16_,SKF_CV20_F17_,SKF_CV20_F18_,SKF_CV20_F19_,SKF_CV50_F00_,SKF_CV50_F01_,SKF_CV50_F02_,SKF_CV50_F03_,SKF_CV50_F04_,SKF_CV50_F05_,SKF_CV50_F06_,SKF_CV50_F07_,SKF_CV50_F08_,SKF_CV50_F09_,SKF_CV50_F10_,SKF_CV50_F11_,SKF_CV50_F12_,SKF_CV50_F13_,SKF_CV50_F14_,SKF_CV50_F15_,SKF_CV50_F16_,SKF_CV50_F17_,SKF_CV50_F18_,SKF_CV50_F19_,SKF_CV50_F20_,SKF_CV50_F21_,SKF_CV50_F22_,SKF_CV50_F23_,SKF_CV50_F24_,SKF_CV50_F25_,SKF_CV50_F26_,SKF_CV50_F27_,SKF_CV50_F28_,SKF_CV50_F29_,SKF_CV50_F30_,SKF_CV50_F31_,SKF_CV50_F32_,SKF_CV50_F33_,SKF_CV50_F34_,SKF_CV50_F35_,SKF_CV50_F36_,SKF_CV50_F37_,SKF_CV50_F38_,SKF_CV50_F39_,SKF_CV50_F40_,SKF_CV50_F41_,SKF_CV50_F42_,SKF_CV50_F43_,SKF_CV50_F44_,SKF_CV50_F45_,SKF_CV50_F46_,SKF_CV50_F47_,SKF_CV50_F48_,SKF_CV50_F49_
13,val,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
26,val,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
29,val,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
37,val,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
55,val,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train

In [12]:
len(cv_folds)

539

**Check that indices in this file is the same as indices in `data` (i.e. train set).**

In [13]:
# Checking that number of times comparing index is Ture, is the same as number of data instances
np.sum(cv_folds.index == data.index) == len(data)

True

In [14]:
# Saveing names of the different folds as we have both 10, 20 and 50 (i.e. SKF_CV10_F00_ etc.)
fold_names = list(cv_folds.columns)

In [15]:
cv_setup = 'CV50'

In [16]:
val_folds = cv_folds[[f for f in fold_names if cv_setup in f]]

In [17]:
val_folds.head()

,SKF_CV50_F00_,SKF_CV50_F01_,SKF_CV50_F02_,SKF_CV50_F03_,SKF_CV50_F04_,SKF_CV50_F05_,SKF_CV50_F06_,SKF_CV50_F07_,SKF_CV50_F08_,SKF_CV50_F09_,SKF_CV50_F10_,SKF_CV50_F11_,SKF_CV50_F12_,SKF_CV50_F13_,SKF_CV50_F14_,SKF_CV50_F15_,SKF_CV50_F16_,SKF_CV50_F17_,SKF_CV50_F18_,SKF_CV50_F19_,SKF_CV50_F20_,SKF_CV50_F21_,SKF_CV50_F22_,SKF_CV50_F23_,SKF_CV50_F24_,SKF_CV50_F25_,SKF_CV50_F26_,SKF_CV50_F27_,SKF_CV50_F28_,SKF_CV50_F29_,SKF_CV50_F30_,SKF_CV50_F31_,SKF_CV50_F32_,SKF_CV50_F33_,SKF_CV50_F34_,SKF_CV50_F35_,SKF_CV50_F36_,SKF_CV50_F37_,SKF_CV50_F38_,SKF_CV50_F39_,SKF_CV50_F40_,SKF_CV50_F41_,SKF_CV50_F42_,SKF_CV50_F43_,SKF_CV50_F44_,SKF_CV50_F45_,SKF_CV50_F46_,SKF_CV50_F47_,SKF_CV50_F48_,SKF_CV50_F49_
13,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
26,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
29,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
37,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
55,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train

In [18]:
for idx, row in val_folds.iterrows():
    # Omgjør hver rad til en liste av True-False, der True hvis markert som 'val':
    bool_row = [s=='val' for s in row.values]
    
    # Sjekk om i nøyaktig én fold
    if np.sum(bool_row) != 1:
        print(f"{row.index} is not in exactly one fold")

OK.

### Fortell PyCaret's `setup` om hvilke fold som skal brukes
We are using the our predefined splits, and thus need to import the `PredefinedSplit`-function.

In [19]:
from pycaret.classification import *
from sklearn.model_selection import PredefinedSplit

In [20]:
val_folds.head()

,SKF_CV50_F00_,SKF_CV50_F01_,SKF_CV50_F02_,SKF_CV50_F03_,SKF_CV50_F04_,SKF_CV50_F05_,SKF_CV50_F06_,SKF_CV50_F07_,SKF_CV50_F08_,SKF_CV50_F09_,SKF_CV50_F10_,SKF_CV50_F11_,SKF_CV50_F12_,SKF_CV50_F13_,SKF_CV50_F14_,SKF_CV50_F15_,SKF_CV50_F16_,SKF_CV50_F17_,SKF_CV50_F18_,SKF_CV50_F19_,SKF_CV50_F20_,SKF_CV50_F21_,SKF_CV50_F22_,SKF_CV50_F23_,SKF_CV50_F24_,SKF_CV50_F25_,SKF_CV50_F26_,SKF_CV50_F27_,SKF_CV50_F28_,SKF_CV50_F29_,SKF_CV50_F30_,SKF_CV50_F31_,SKF_CV50_F32_,SKF_CV50_F33_,SKF_CV50_F34_,SKF_CV50_F35_,SKF_CV50_F36_,SKF_CV50_F37_,SKF_CV50_F38_,SKF_CV50_F39_,SKF_CV50_F40_,SKF_CV50_F41_,SKF_CV50_F42_,SKF_CV50_F43_,SKF_CV50_F44_,SKF_CV50_F45_,SKF_CV50_F46_,SKF_CV50_F47_,SKF_CV50_F48_,SKF_CV50_F49_
13,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
26,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
29,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
37,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
55,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train

Add as column i dataframe:

In [21]:
data.head()

,AGE,RAVLT_immediate,AVDEL30MIN_neuro,AVDELTOT_neuro,TRAASCOR_neuro,TRABSCOR_neuro,CATANIMSC_neuro,GDTOTAL_gds,ANARTERR_neuro,LRHHC_n_long,Apoe4_,Subgroup_,Subgroup_num_,Usage_,PTGENDER,Gender_num_
13,80.0,36.0,1.0,8.0,47.0,139.0,16.0,1.0,4.0,0.003458,0.0,cAD,1,train,Female,1
26,76.8,27.0,5.0,10.0,61.0,300.0,19.0,4.0,23.0,0.005251,0.0,sMCI,0,train,Male,0
29,70.9,22.0,0.0,0.0,18.0,145.0,18.0,2.0,12.0,0.003026,1.0,cAD,1,train,Female,1
37,72.8,29.0,1.0,8.0,40.0,101.0,17.0,1.0,6.0,0.002767,0.0,cAD,1,train,Male,0
55,77.6,30.0,2.0,14.0,150.0,300.0,12.0,0.0,9.0,0.002814,0.0,cAD,1,train,Male,0

In [22]:
def get_fold_nb(idx):
    """
    Input: an index (i.e. instance id) in the val_fold df
    Return: the index in the corresponding val_fold line where it says 'val'
    """
    
    folds = list(val_folds.loc[idx].values)
    #print(folds)
    return folds.index('val')

Adding this as new column in our `data` dataframe

In [34]:
data['fold_nb'] = [get_fold_nb(idx) for idx in list(data.index)]

Look at some arbitrary instances to checking that it is correct:

In [35]:
data[120:130]

,AGE,RAVLT_immediate,AVDEL30MIN_neuro,AVDELTOT_neuro,TRAASCOR_neuro,TRABSCOR_neuro,CATANIMSC_neuro,GDTOTAL_gds,ANARTERR_neuro,LRHHC_n_long,Apoe4_,Subgroup_,Subgroup_num_,Usage_,PTGENDER,Gender_num_,fold_nb
1476,80.4,46.0,9.0,15.0,29.0,82.0,13.0,1.0,7.0,0.004664,0.0,sMCI,0,train,Female,1,8
1491,80.9,29.0,2.0,11.0,73.0,84.0,21.0,2.0,2.0,0.003177,1.0,cAD,1,train,Male,0,13
1497,69.2,33.0,3.0,14.0,48.0,230.0,11.0,3.0,15.0,0.003481,1.0,cAD,1,train,Female,1,14
1504,65.1,38.0,0.0,5.0,25.0,73.0,15.0,1.0,17.0,0.004641,1.0,cAD,1,train,Female,1,14
1521,82.8,24.0,2.0,12.0,69.0,118.0,14.0,3.0,17.0,0.002981,1.0,sMCI,0,train,Male,0,8
1540,79.6,24.0,1.0,4.0,43.0,143.0,19.0,2.0,13.0,0.003408,1.0,sMCI,0,train,Male,0,8
1546,75.6,36.0,0.0,15.0,61.0,205.0,11.0,1.0,21.0,0.004062,1.0,cAD,1,train,Female,1,14
1552,82.0,29.0,0.0,1.0,80.0,204.0,18.0,2.0,4.0,0.002994,1.0,cAD,1,train,Female,1,14
1579,71.2,51.0,13.0,15.0,43.0,106.0,21.0,0.0,2.0,0.004881,0.0,sMCI,0,train,Male,0,9
1590,74.1,42.0,8.0,11.0,34.0,55.0,18.0,0.0,3.0,0.004407,0.0,sMCI,0,train,Female,1,9

In [36]:
val_folds[120:130]

,SKF_CV50_F00_,SKF_CV50_F01_,SKF_CV50_F02_,SKF_CV50_F03_,SKF_CV50_F04_,SKF_CV50_F05_,SKF_CV50_F06_,SKF_CV50_F07_,SKF_CV50_F08_,SKF_CV50_F09_,SKF_CV50_F10_,SKF_CV50_F11_,SKF_CV50_F12_,SKF_CV50_F13_,SKF_CV50_F14_,SKF_CV50_F15_,SKF_CV50_F16_,SKF_CV50_F17_,SKF_CV50_F18_,SKF_CV50_F19_,SKF_CV50_F20_,SKF_CV50_F21_,SKF_CV50_F22_,SKF_CV50_F23_,SKF_CV50_F24_,SKF_CV50_F25_,SKF_CV50_F26_,SKF_CV50_F27_,SKF_CV50_F28_,SKF_CV50_F29_,SKF_CV50_F30_,SKF_CV50_F31_,SKF_CV50_F32_,SKF_CV50_F33_,SKF_CV50_F34_,SKF_CV50_F35_,SKF_CV50_F36_,SKF_CV50_F37_,SKF_CV50_F38_,SKF_CV50_F39_,SKF_CV50_F40_,SKF_CV50_F41_,SKF_CV50_F42_,SKF_CV50_F43_,SKF_CV50_F44_,SKF_CV50_F45_,SKF_CV50_F46_,SKF_CV50_F47_,SKF_CV50_F48_,SKF_CV50_F49_
1476,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
1491,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
1497,train,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
1504,train,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
1521,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
1540,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
1546,train,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
1552,train,train,train,train,train,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
1579,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train
1590,train,train,train,train,train,train,train,train,train,val,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train,train

In [37]:
ps = PredefinedSplit(test_fold=data['fold_nb'])

In [38]:
ps

PredefinedSplit(test_fold=array([ 0,  0, ..., 49, 49]))

Checking that the folds contain the correct instances:

These are the rows that should belong to the first fold according to our predefined split. First there is an array with the rows for training, followed by an array with those in the validation fold:

In [39]:
list(ps.split())[0]

(array([  8,   9,  11,  12,  15,  16,  17,  18,  19,  20,  21,  22,  23,
         24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
         37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
         50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
         76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
        167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
        180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
        193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
        206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
        219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
        232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
        245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257,
        258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
        271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283,
        284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296,
        297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309,
        310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322,
        323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335,
        336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348,
        349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361,
        362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374,
        375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387,
        388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400,
        401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413,
        414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426,
        427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439,
        440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452,
        453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465,
        466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478,
        479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491,
        492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
        505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
        518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530,
        531, 532, 533, 534, 535, 536, 537, 538]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 13, 14]))

Det svarer til at disse instansene skal være i val:

In [40]:
# This mean that these instances should be in validation:
list(ps.split())[0][1]

array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 13, 14])

In [41]:
len(data.iloc[list(ps.split())[0][1]])

11

In [42]:
data.iloc[list(ps.split())[0][1]]

,AGE,RAVLT_immediate,AVDEL30MIN_neuro,AVDELTOT_neuro,TRAASCOR_neuro,TRABSCOR_neuro,CATANIMSC_neuro,GDTOTAL_gds,ANARTERR_neuro,LRHHC_n_long,Apoe4_,Subgroup_,Subgroup_num_,Usage_,PTGENDER,Gender_num_,fold_nb
13,80.0,36.0,1.0,8.0,47.0,139.0,16.0,1.0,4.0,0.003458,0.0,cAD,1,train,Female,1,0
26,76.8,27.0,5.0,10.0,61.0,300.0,19.0,4.0,23.0,0.005251,0.0,sMCI,0,train,Male,0,0
29,70.9,22.0,0.0,0.0,18.0,145.0,18.0,2.0,12.0,0.003026,1.0,cAD,1,train,Female,1,0
37,72.8,29.0,1.0,8.0,40.0,101.0,17.0,1.0,6.0,0.002767,0.0,cAD,1,train,Male,0,0
55,77.6,30.0,2.0,14.0,150.0,300.0,12.0,0.0,9.0,0.002814,0.0,cAD,1,train,Male,0,0
62,66.5,29.0,3.0,10.0,27.0,94.0,9.0,1.0,32.0,0.003679,1.0,cAD,1,train,Male,0,0
75,81.0,26.0,0.0,7.0,38.0,201.0,13.0,2.0,11.0,0.003298,0.0,cAD,1,train,Female,1,0
89,70.0,32.0,4.0,8.0,31.0,61.0,13.0,1.0,35.0,0.004214,1.0,sMCI,0,train,Male,0,0
108,75.1,23.0,0.0,6.0,26.0,54.0,23.0,1.0,10.0,0.003028,0.0,sMCI,0,train,Male,0,0
130,70.3,22.0,2.0,13.0,60.0,170.0,5.0,2.0,42.0,0.004205,1.0,sMCI,0,train,Female,1,0
137,60.7,50.0,11.0,13.0,18.0,41.0,17.0,2.0,11.0,0.005008,0.0,sMCI,0,train,Female,1,0

Comparing to our `fold_nb`-column from above:

In [43]:
len(data.loc[data['fold_nb']==0])

11

In [44]:
data.loc[data['fold_nb']==0]

,AGE,RAVLT_immediate,AVDEL30MIN_neuro,AVDELTOT_neuro,TRAASCOR_neuro,TRABSCOR_neuro,CATANIMSC_neuro,GDTOTAL_gds,ANARTERR_neuro,LRHHC_n_long,Apoe4_,Subgroup_,Subgroup_num_,Usage_,PTGENDER,Gender_num_,fold_nb
13,80.0,36.0,1.0,8.0,47.0,139.0,16.0,1.0,4.0,0.003458,0.0,cAD,1,train,Female,1,0
26,76.8,27.0,5.0,10.0,61.0,300.0,19.0,4.0,23.0,0.005251,0.0,sMCI,0,train,Male,0,0
29,70.9,22.0,0.0,0.0,18.0,145.0,18.0,2.0,12.0,0.003026,1.0,cAD,1,train,Female,1,0
37,72.8,29.0,1.0,8.0,40.0,101.0,17.0,1.0,6.0,0.002767,0.0,cAD,1,train,Male,0,0
55,77.6,30.0,2.0,14.0,150.0,300.0,12.0,0.0,9.0,0.002814,0.0,cAD,1,train,Male,0,0
62,66.5,29.0,3.0,10.0,27.0,94.0,9.0,1.0,32.0,0.003679,1.0,cAD,1,train,Male,0,0
75,81.0,26.0,0.0,7.0,38.0,201.0,13.0,2.0,11.0,0.003298,0.0,cAD,1,train,Female,1,0
89,70.0,32.0,4.0,8.0,31.0,61.0,13.0,1.0,35.0,0.004214,1.0,sMCI,0,train,Male,0,0
108,75.1,23.0,0.0,6.0,26.0,54.0,23.0,1.0,10.0,0.003028,0.0,sMCI,0,train,Male,0,0
130,70.3,22.0,2.0,13.0,60.0,170.0,5.0,2.0,42.0,0.004205,1.0,sMCI,0,train,Female,1,0
137,60.7,50.0,11.0,13.0,18.0,41.0,17.0,2.0,11.0,0.005008,0.0,sMCI,0,train,Female,1,0

## Pycaret setup

Setting up PyCaret experiment
- correct train and test data split specified in `2.0-random_forest`-notebook
- correct taget (i.e. `Subgroup_num_`), 
- dropping `Subgroup_`, `fold_nb` and `Usage_`, 
- using the predefined cross validation set up, and 
- specifying a `Session_id`

In [45]:
clf = setup(data, test_data=data_unseen, target = 'Subgroup_num_', 
            ignore_features=['Subgroup_', 'fold_nb','Usage_'], fold_strategy=ps, session_id=1138)

# Construct models

In [46]:
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,pycaret.internal.tunable.TunableMLPClassifier,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
catboost,CatBoost Classifier,catboost.core.CatBoostClassifier,True

Selecting the top 5 best performing:

In [47]:
top5 = compare_models(n_select=5, sort='Accuracy')

Tuning the selected models:

In [48]:
top5

[LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                            solver='svd', store_covariance=False, tol=0.0001),
 ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                      criterion='gini', max_depth=None, max_features='auto',
                      max_leaf_nodes=None, max_samples=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                      oob_score=False, random_state=1138, verbose=0,
                      warm_start=False),
 <catboost.core.CatBoostClassifier at 0x7f98d7b7c910>,
 AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                    n_estimators=50, random_state=1138),
 LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                    intercept_scaling=1, l1_ratio=None, max_iter=1000,
                    multi_class='auto', n_jobs=None, penalty='l2',
                    random_state=1138, solver='lbfgs', tol=0.0001, verbose=0,
                    warm_start=False)]

In [49]:
tuned_top5 = [tune_model(i) for i in top5]

Bagging ensembles of all top 5:

In [50]:
tuned_top5

[LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage='auto',
                            solver='lsqr', store_covariance=False, tol=0.0001),
 ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                      class_weight='balanced_subsample', criterion='entropy',
                      max_depth=10, max_features=1.0, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.002,
                      min_impurity_split=None, min_samples_leaf=2,
                      min_samples_split=5, min_weight_fraction_leaf=0.0,
                      n_estimators=260, n_jobs=-1, oob_score=False,
                      random_state=1138, verbose=0, warm_start=False),
 <catboost.core.CatBoostClassifier at 0x7f98d6adea50>,
 AdaBoostClassifier(algorithm='SAMME', base_estimator=None, learning_rate=0.031,
                    n_estimators=250, random_state=1138),
 LogisticRegression(C=0.704, class_weight={}, dual=False, fit_intercept=True,
                    intercept_scaling=1, l1_ratio=None, max_iter=1000,
                    multi_class='auto', n_jobs=None, penalty='l2',
                    random_state=1138, solver='lbfgs', tol=0.0001, verbose=0,
                    warm_start=False)]

In [51]:
bagged_top5 = [ensemble_model(i) for i in tuned_top5]

Bagging of the non-tuned top 5 models:

In [52]:
bagged_top5 = [ensemble_model(i) for i in top5]

Blened by a `VotingClassifier`:

In [53]:
nontuned_blender = blend_models(estimator_list = top5)

In [54]:
tuned_blender = blend_models(estimator_list = tuned_top5)

In [55]:
bagged_blender = blend_models(estimator_list = bagged_top5)

By optimizing for Accuracy, we use the `auto_ml`-function to the best performing model:

In [57]:
best = automl(optimize='Accuracy')

This is the best:

In [58]:
best

BaggingClassifier(base_estimator=ExtraTreesClassifier(bootstrap=False,
                                                      ccp_alpha=0.0,
                                                      class_weight='balanced_subsample',
                                                      criterion='entropy',
                                                      max_depth=10,
                                                      max_features=1.0,
                                                      max_leaf_nodes=None,
                                                      max_samples=None,
                                                      min_impurity_decrease=0.002,
                                                      min_impurity_split=None,
                                                      min_samples_leaf=2,
                                                      min_samples_split=5,
                                                      min_weight_fraction_leaf=0.0,
                                                      n_estimators=260,
                                                      n_jobs=-1,
                                                      oob_score=False,
                                                      random_state=1138,
                                                      verbose=0,
                                                      warm_start=False),
                  bootstrap=True, bootstrap_features=False, max_features=1.0,
                  max_samples=1.0, n_estimators=10, n_jobs=None,
                  oob_score=False, random_state=1138, verbose=0,
                  warm_start=False)

> The bagged blender was the best performing model, save this:

# Exporting model to results directory

In [ ]:
save_model(best, 'best_model_accuracy_top5')

In [ ]:
save_model(bagged_blender, 'best_blended_accuracy_top5')

# Prediker på test og tolk resultater

Se notebook `pycaret_test-asl-201121-predict_and_interpret.ipynb`

In [62]:
test = pull()
print(test)

                                    Model  Accuracy     AUC  Recall   Prec.  \
lda          Linear Discriminant Analysis    0.7207  0.7951  0.7340  0.7166
et                 Extra Trees Classifier    0.7136  0.7808  0.7093  0.7084
catboost              CatBoost Classifier    0.7133  0.7797  0.7233  0.7023
ada                  Ada Boost Classifier    0.7120  0.7384  0.7193  0.7153
rf               Random Forest Classifier    0.7033  0.7821  0.6987  0.7036
nb                            Naive Bayes    0.7027  0.7528  0.7700  0.6865
ridge                    Ridge Classifier    0.7025  0.0000  0.7420  0.6931
lightgbm  Light Gradient Boosting Machine    0.6858  0.7559  0.6793  0.6727
xgboost         Extreme Gradient Boosting    0.6840  0.7447  0.6800  0.6789
qda       Quadratic Discriminant Analysis    0.6805  0.7480  0.6740  0.6648
gbc          Gradient Boosting Classifier    0.6705  0.7324  0.6920  0.6536
dt               Decision Tree Classifier    0.6425  0.6417  0.6400  0.6388
knn                K Neighbors Classifier    0.6245  0.6460  0.6633  0.6124
svm                   SVM - Linear Kernel    0.6109  0.0000  0.6107  0.5685

              F1   Kappa     MCC  TT (Sec)
lda       0.7101  0.4425  0.4573    0.0160
et        0.6967  0.4255  0.4357    0.5272
catboost  0.6964  0.4247  0.4390    1.0254
ada       0.7000  0.4239  0.4381    0.1140
rf        0.6822  0.4041  0.4201    0.3314
nb        0.7085  0.4085  0.4304    0.0154
ridge     0.7008  0.4061  0.4188    0.0114
lightgbm  0.6629  0.3698  0.3808    0.2050
xgboost   0.6662  0.3658  0.3776    0.2808
qda       0.6537  0.3571  0.3735    0.0160
gbc       0.6552  0.3406  0.3555    0.0950
dt        0.6184  0.2835  0.2994    0.0196
knn       0.6129  0.2489  0.2668    0.2016
svm       0.5324  0.2239  0.2623    0.1852

In [ ]:
%matplotlib inline
plot_model(bagged_blender, 'confusion_matrix')

In [ ]:
plot_model(best, 'confusion_matrix')